title: Jinlong Yang's Homepage
page-top-title: Jinlong Yang
top-section-bg-text: Computer Science
home-subtitle: Jinlong Yang&ensp;|&ensp;杨金龙
copyright-text: '&copy;  Jinlong Yang 2025-2026. All Rights Reserved.'
